config/routes.rb
Fnz::Application.routes.draw do
  #mount TzMagic::Engine => "/tz_magic"

  #authenticated :user do
  #  root :to => 'home#index'
  #end

  get "/login",  to: "sso_sessions#show"
  match '/logout', to: "sso_sessions#destroy", via: [:get, :delete]
  devise_for :users, :controllers => { :registrations => "registrations"}
  resource :sso_session

  resources :user_businesses
  resources :businesses do
    resources :month_tag_totals, only: [:index]
    resources :admparts do
      get "/ym/:year/:month", to: "admparts#show", as: :dated_admpart, on: :collection
      member do
        get :attendance_detail
      end
      collection do
        get :current, to: "admparts#show", id: :current
      end
    end
    resources :accounts do
      member do
        patch :update_balance
      end
      resources :transactions, :only => [:index] do
        get :stats, :on => :collection
      end
      resources :debits, :controller => 'transactions', :only => [:index]
      resources :credits, :controller => 'transactions', :only => [:index]
      resources :transfers, :controller => 'transactions', :only => [:index]
      resources :balance_checks
    end
    resources :recurrent_transactions
    resources :transactions do
      resources :transaction_spliters, only: [:new, :create] do
        collection do
          get :new_n_split
          post :create_n_split
        end
      end
      member do
        get :receipt
      end
      collection do
        get :batch_edit
        put :batch_update
        get :stats
      end
    end
    resources :debits, :controller => 'transactions', :only => [:index, :update]
    resources :credits, :controller => 'transactions', :only => [:index, :update]
    resources :transfers, :controller => 'transactions', :only => [:index, :update]
    resources :tags do
      collection do
        # required for Sortable GUI server side actions
        post :rebuild
      end
    end
    resources :month_exchange_rates do
      collection do
        get :get_rate
      end
      member do
        put :refresh_rate
      end
    end
    resources :transaction_rules
    resources :contacts
    resources :agents
    resources :products
    resources :sales do
      get :stats, :on => :collection
      resource :payment, :only => [:new, :create]
    end
    resources :payment_types
    resources :installments
    resource :payment, :only => [:new, :create]
    resources :memberships do
      resource :payment, :only => [:new, :create]
      resources :installments do
      	resource :payment, :only => [:new, :create]
      end
      resource :enrollment do
        resource :payment, :only => [:new, :create]
      end
      get :overview, :on => :collection
      get :stats, :on => :collection
      get :stats_detail, :on => :collection
    end
    resources :inscriptions do
      resources :transactions
    end
    resources :imports do
      put :process_csv, :on => :member
      get :errors, :on => :member
    end
    resources :users
    resources :closures
    resource :closure do
      get :print, :on => :member
    end
  end
  resources :debits, :controller => 'transactions', :except => [:index]
  resources :credits, :controller => 'transactions', :except => [:index]
  resources :transfers, :controller => 'transactions', :except => [:index]
  resources :custom_prizes

  resources :receipts
  get "/r/:id", to: "receipts#show"

  get 'messages', to: 'messages#catch_message'
  get 'sns', to: 'messages#sns'
  post 'sns', to: 'messages#sns'

  namespace 'admin' do
    resources :businesses, only: [:index, :show, :edit, :update, :destroy]
  end

  namespace 'api' do
    namespace 'v0' do
      resources :imports, only: [:create, :show] do
        member do
          get :failed_rows # GET /api/v0/imports/:id/failed_rows
        end
      end
      resources :businesses do
        resources :contacts do
          resource :current_membership
        end
	      get 'current_memberships', to: "current_memberships#index"
      end
      resources :merges, only: [:create]
      resources :inscriptions, only: [:create]
      namespace 'notifications' do
        post :mercadopago
      end
    end
  end

  root to: "home#index"
end

app/models/business/has_contacts.rb
module Business::HasContacts
  extend ActiveSupport::Concern

  included do

    has_many :contacts

    # encola actualización de alumnos y ex-alumnos
    def queue_syncs_from_crm
      per_page = 500
      page = 1
      loop do
        pcs = CrmLegacyContact.paginate(
          account_name: padma_id,
          page: page,
          per_page: per_page,
          where: {local_status: %W(student former_student)}
        )
        break if pcs.blank?
        pcs.each do |pc|
          Delayed::Job.enqueue FetchCrmContactJob.new(id: pc.id, business_padma_id: padma_id)
        end
        page += 1
      end
    end
  end
end

app/models/business/has_currency.rb
module Business::HasCurrency
  extend ActiveSupport::Concern

  included do

    before_validation :set_default_currency
    validates :currency_code, presence: true
    after_save :update_calculations

    def currency_symbol
      if currency_code
        Currency.find(currency_code).try(:symbol)
      else
        Currency.find("usd").try(:symbol)
      end
    end

    def update_calculations
      if currency_code_changed?
        month_exchange_rates.each &:update_calculations
      end
    end

    private

    def set_default_currency
      if currency_code.nil?
        if (padma_account = padma)
          self.currency_code = case padma_account.country
            when "Brazil"
              "brl"
            when "Argentina"
              "ars"
            else
              "usd"
          end
        else
          self.currency_code = "usd"
        end
      end

    end

  end
end

app/controllers/admin/businesses_controller.rb
class Admin::BusinessesController < Admin::ApplicationController
  def index
    @businesses = Business.all
  end

  def show
    @business = Business.find(params[:id])
  end

  def edit
    @business = Business.find(params[:id])
  end

   # PUT /businesses/1
  # PUT /businesses/1.json
  def update
    @business = Business.find(params[:id])

    respond_to do |format|
      if @business.update_attributes(params[:business])
        format.html { redirect_to admin_business_path(@business), notice: 'Business was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /businesses/1
  # DELETE /businesses/1.json
  def destroy
    @business = Business.find(params[:id])
    @business.destroy

    respond_to do |format|
      format.html { redirect_to admin_businesses_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/businesses_controller.rb
class BusinessesController < UserApplicationController
  def index
    @businesses = current_user.user_businesses
  end

  def show
    @business = current_user.businesses.find(params[:id])
  end

  def edit
    @business = current_user.owned_businesses.find(params[:id])
  end

  def new
    @business = current_user.owned_businesses.new(business_params)
  end

  # POST /businesses
  # POST /businesses.json
  def create
      @business = current_user.owned_businesses.new(business_params)

    respond_to do |format|
      if @business.save
        format.html { redirect_to business_path(@business), notice: 'Business was successfully created.' }
        format.json { render json: @business, status: :created, location: @business }
      else
        format.html { render action: "new" }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /businesses/1
  # PUT /businesses/1.json
  def update
    @business = Business.find(params[:id])
    authorize! :update, @business

    respond_to do |format|
      if @business.update_attributes(business_params || {})
        format.html { redirect_to business_path(@business), notice: 'Business was successfully updated.' }
        format.json do
          respond_with_bip(@business.becomes(Business), param: param_key)
        end
      else
        format.html { render action: "edit" }
        format.json do
          respond_with_bip(@business.becomes(Business), param: param_key)
        end
      end
    end
  end

  # DELETE /businesses/1
  # DELETE /businesses/1.json
  def destroy
    @business = current_user.owned_businesses.find(params[:id])
    @business.destroy

    respond_to do |format|
      format.html { redirect_to businesses_url }
      format.json { head :no_content }
    end
  end

  private

  def business_params
    params.require(:business).permit(
      :type,
      :name,
      :owner_id,
      :padma_id,
      :synchronzied_at,
      :send_weekly_reports,
      :transactions_enabled,
      :share_enabled,
      :use_calendar_installments,
      :currency_code,
      :block_transactions_before,
      :use_learn_checkins
    ) if params[:business].present?
  end

  def param_key
    if params[:school]
      :school
    else
      :business
    end
  end
end

app/views/businesses/_edit_sidebar.html.erb
<ul class="nav nav-pills nav-stacked" id="edit-sidebar">
  <% if @business.is_a?(School) || @business.is_a?(Event) %>
  <!--<li class="<%= 'active' if controller.controller_name == "agents" %>"><%= link_to content_tag(:i, "", :class => "icon-sitemap") + t("businesses.edit_sidebar.#{@business.type.downcase}.manage_agents"), business_agents_path(@business) %></li>-->
  <li class="<%= 'active' if controller.controller_name == "payment_types" %>"><%= link_to content_tag(:i, "", :class => "icon-money") + t('businesses.edit_sidebar.manage_payment_types'), business_payment_types_path(@business) %></li>
  <% end -%>
  <% if @business.transactions_enabled? %>
  <li class="<%= 'active' if controller.controller_name == "tags" %>"><%= link_to content_tag(:i, "", :class => "icon-tags") + t('businesses.edit_sidebar.manage_tags'), business_tags_path(@business) %></li>
  <% end %>
  <% if @business.transactions_enabled? %>
  <li class="<%= 'active' if controller.controller_name == "accounts" %>"><%= link_to content_tag(:i, "", :class => "icon-folder-open") + t('businesses.edit_sidebar.manage_accounts'), business_accounts_path(@business) %></li>
  <% end %>
  <% if @business.transactions_enabled? %>
    <li class="<%= 'active' if controller.controller_name == "imports" %>"><%= link_to content_tag(:i, "", :class => "icon-upload") + t('businesses.edit_sidebar.manage_imports'), business_imports_path(@business) %></li>
    <li class="<%= 'active' if controller.controller_name == "transaction_rules" %>"><%= link_to content_tag(:i, "", :class => "icon-cogs") + _("Reglas de automatización"), business_transaction_rules_path(@business) %></li>
    <li class="<%= 'active' if controller.controller_name == "month_exchange_rates" %>"><%= link_to content_tag(:i, "", :class => "icon-money") + t("month_exchange_rates.index.title"), business_month_exchange_rates_path(@business) %></li>
  <% end %>
  <% if @business.share_enabled? %>
    <!-- <li class="<%= 'active' if controller.controller_name == "users" %>"><%= link_to content_tag(:i, "", :class => "icon-globe") + t('businesses.edit_sidebar.manage_users'), business_users_path(@business) %></li> -->
  <% end %>
</ul>

app/views/businesses/_form.html.erb
<%= simple_form_for(@business, :as => :business, :validate => true, :url => form_url, :html => {:class => "form-horizontal"}) do |f| %>
  <%= f.input :name %>

  <%= f.input :currency_code, :as => :select, :collection => SUPPORTED_CURRENCIES %>  

	<%= f.input :send_weekly_reports %>
	<%= f.input :use_calendar_installments %>
	<%= f.input :use_learn_checkins %>


  <%= f.button :submit, :class => "btn btn-primary" %>
<% end %>

app/views/businesses/_sidebar.html.erb
<% if @business.present? && @business.persisted? %>
<p><%= I18n.t('businesses.sidebar.title') %>
<% if can? :manage, @business.accounts.build %>
(<%= link_to t('businesses.sidebar.manage'), business_accounts_path(@business) %>)
<% end %>
:
<ul class="nav nav-pills nav-stacked">
  <% @business.accounts.order("name").each do |account| %>
  	<% unless account.new_record? %>
      <li class="<%= 'active' if @account.present? && account.id == @account.id %>">
        <%= link_to business_account_transactions_path(@business, account) do %>
          <%= account.name.html_safe %>
          <span class="balance pull-right account_<%= account.id %>_balance">
            <%= number_to_currency(account.balance, unit: account.currency.symbol) %>
            <% if account.current_balance_checked? && account.last_balance_check %>
              <%= content_tag(:i,
                              "",
                              class: "icon-ok account_balance_checked",
                              title: _("Saldo chequeado el %{date}") % { date: l(account.last_balance_check.checked_at)}).html_safe %>
            <% else %>
              <i class="account_balance_dirty"></i>
            <% end %>
          </span>
        <% end %>
      </li>
      <% end %>
  <% end %>
  <li><a></a></li>
  <% @business.accounts.calculate_total_balance_per_currency.each do |cur,balance| %>
    <li>
      <a>
        <%= _("Total %{cur}") % {cur: cur} %>:
        <%= number_to_currency( balance , unit: Currency.find(cur).symbol ) %>
      </a>
    </li>
  <% end %>
  <li>
    <a>
      <b>
      <%= t(".total_balance_in_business_currency") %>:
      <%= number_to_currency( @business.accounts.calculate_total_balance , unit: Currency.find(@business.currency_code).symbol ) %>
      </b>
    </a>
  </li>
  <li><a></a></li>
  <% @business.accounts.calculate_pending_balance_per_currency.each do |cur,balance| %>
    <li>
      <a>
        <%= _("Total %{cur} pendientes") % {cur: cur} %>:
        <%= number_to_currency( balance , unit: Currency.find(cur).symbol ) %>
      </a>
    </li>
  <% end %>
</ul>

  <% if can?(:update, @business) %>
  <ul>
    <li>
      <%= t("activerecord.attributes.business.block_transactions_before") %>
      <%= best_in_place @business.becomes(Business), :block_transactions_before, display_with: lambda { |d| d.to_s(:short) } %>
      <br>
      <small><%= t(".prevents_transactions_before_this_date") %></small>
    </li>
  </ul>
    <% end %>
</p>
<% end %>

app/views/businesses/edit.html.erb
<% content_for :sidebar do %>
  <%= render :partial => 'edit_sidebar' %>
<% end %>

<h2><%= t('businesses.edit.title') %></h2>

<%= render :partial => 'form', :locals => {:form_url => business_path(@business)} %>

app/views/businesses/index.html.erb
<% content_for :secondary_navigation do %>
<% end %>

<% content_for :sidebar do %>
  <h3><%= t('businesses.index.title') %></h3>
<% end %>

<% content_for :top do %>
<% end %>

<table id="businesses" class="table table-striped table-bordered">
  <tr>
    <th><%= Business.human_attribute_name(:name) %></th>
    <th></th>
  </tr>
  <% @businesses.each do |user_business| %>
    <tr>
      <td><%= link_to user_business.business.name, business_path(user_business.business) %></td>
      <td>
        <%= link_to content_tag(:i, "", :class => "icon-eye-#{user_business.show_on_menu? ? 'open' : 'close'}"), user_business_path(user_business, :user_business => {:show_on_menu => !user_business.show_on_menu}), :method => 'put' %>
        <%= link_to content_tag(:i, "", :class => "icon-trash"), business_path(user_business.business), data: {:confirm => 'Are you sure you want to delete this item?'}, :method => 'delete' %>
      </td>
    </tr>
  <% end -%>
</table>

app/views/businesses/new.html.erb
<h2>New Business</h2>

<%= render :partial => 'form', :locals => {:form_url => businesses_path}  %>

<%= link_to 'Back', businesses_path %>

app/views/businesses/show.html.erb
<% content_for :sidebar do %>
    <%= render :partial => 'edit_sidebar' %>
<% end %>

<p><b><%= Business.human_attribute_name(:name) %>:</b> <%= @business.name %> </p>
<p><b><%= Business.human_attribute_name(:owner) %>:</b>  <%= @business.owner.drc_uid %> </p>