config/routes.rb
Fnz::Application.routes.draw do
  #mount TzMagic::Engine => "/tz_magic"

  #authenticated :user do
  #  root :to => 'home#index'
  #end

  get "/login",  to: "sso_sessions#show"
  match '/logout', to: "sso_sessions#destroy", via: [:get, :delete]
  devise_for :users, :controllers => { :registrations => "registrations"}
  resource :sso_session

  resources :user_businesses
  resources :businesses do
    resources :month_tag_totals, only: [:index]
    resources :admparts do
      get "/ym/:year/:month", to: "admparts#show", as: :dated_admpart, on: :collection
      member do
        get :attendance_detail
      end
      collection do
        get :current, to: "admparts#show", id: :current
      end
    end
    resources :accounts do
      member do
        patch :update_balance
      end
      resources :transactions, :only => [:index] do
        get :stats, :on => :collection
      end
      resources :debits, :controller => 'transactions', :only => [:index]
      resources :credits, :controller => 'transactions', :only => [:index]
      resources :transfers, :controller => 'transactions', :only => [:index]
      resources :balance_checks
    end
    resources :recurrent_transactions
    resources :transactions do
      resources :transaction_spliters, only: [:new, :create] do
        collection do
          get :new_n_split
          post :create_n_split
        end
      end
      member do
        get :receipt
      end
      collection do
        get :batch_edit
        put :batch_update
        get :stats
      end
    end
    resources :debits, :controller => 'transactions', :only => [:index, :update]
    resources :credits, :controller => 'transactions', :only => [:index, :update]
    resources :transfers, :controller => 'transactions', :only => [:index, :update]
    resources :tags do
      collection do
        # required for Sortable GUI server side actions
        post :rebuild
      end
    end
    resources :month_exchange_rates do
      collection do
        get :get_rate
      end
      member do
        put :refresh_rate
      end
    end
    resources :transaction_rules
    resources :contacts
    resources :agents
    resources :products
    resources :sales do
      get :stats, :on => :collection
      resource :payment, :only => [:new, :create]
    end
    resources :payment_types
    resources :installments
    resource :payment, :only => [:new, :create]
    resources :memberships do
      resource :payment, :only => [:new, :create]
      resources :installments do
      	resource :payment, :only => [:new, :create]
      end
      resource :enrollment do
        resource :payment, :only => [:new, :create]
      end
      get :overview, :on => :collection
      get :stats, :on => :collection
      get :stats_detail, :on => :collection
    end
    resources :inscriptions do
      resources :transactions
    end
    resources :imports do
      put :process_csv, :on => :member
      get :errors, :on => :member
    end
    resources :users
    resources :closures
    resource :closure do
      get :print, :on => :member
    end
  end
  resources :debits, :controller => 'transactions', :except => [:index]
  resources :credits, :controller => 'transactions', :except => [:index]
  resources :transfers, :controller => 'transactions', :except => [:index]
  resources :custom_prizes

  resources :receipts
  get "/r/:id", to: "receipts#show"

  get 'messages', to: 'messages#catch_message'
  get 'sns', to: 'messages#sns'
  post 'sns', to: 'messages#sns'

  namespace 'admin' do
    resources :businesses, only: [:index, :show, :edit, :update, :destroy]
  end

  namespace 'api' do
    namespace 'v0' do
      resources :imports, only: [:create, :show] do
        member do
          get :failed_rows # GET /api/v0/imports/:id/failed_rows
        end
      end
      resources :businesses do
        resources :contacts do
          resource :current_membership
        end
	      get 'current_memberships', to: "current_memberships#index"
      end
      resources :merges, only: [:create]
      resources :inscriptions, only: [:create]
      namespace 'notifications' do
        post :mercadopago
      end
    end
  end

  root to: "home#index"
end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  belongs_to :membership
  belongs_to :agent
  has_many :enrollment_transactions
  has_many :trans, foreign_key: 'transaction_id', class_name: "Transaction", :through => :enrollment_transactions

  validates :membership, :presence => true
  validates :agent, :presence => true
  validates :value, :presence => true
  validates :enrolled_on, :presence => true

  # Setup accessible (or protected) attributes for your model
  #attr_accessible :membership_id, :agent_id, :value, :enrolled_on, :transactions_attributes, :enrollment_transactions_attributes
  accepts_nested_attributes_for :trans, allow_destroy: true
  accepts_nested_attributes_for :enrollment_transactions, :reject_if => proc { |s| s['transaction_id'].blank? }

  scope :this_month, -> { where {(enrolled_on.gteq Date.today.beginning_of_month.beginning_of_day) & (enrolled_on.lteq Date.today.end_of_month.end_of_day)} }

  def pending?
    !trans.empty? && trans.any? { |t| t.pending? }
  end

  def complete?
    !trans.empty? && trans.all? { |t| t.created? || t.reconciled? }
  end

  def status
    if pending?
      :pending
    elsif complete?
      :complete
    else
      :incomplete
    end
  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < UserApplicationController
  before_filter :get_context

  def show
  end

  def edit
  	date = @enrollment.enrolled_on || Date.today
  	@transactions = @business.trans.credits.where {(transaction_at.gteq date - 1.month) & (transaction_at.lteq  date + 1.month)}
  end

  def new
    @enrollment = @membership.build_enrollment(enrollment_params)
  	date = @enrollment.enrolled_on || Date.today
  	@transactions = @business.trans.credits.where {(transaction_at.gteq date - 1.month) & (transaction_at.lteq  date + 1.month)}
  end

  # POST /enrollments
  # POST /enrollments.json
  def create
    @enrollment = @membership.build_enrollment(enrollment_params)

    respond_to do |format|
      if @enrollment.save
        format.html { redirect_to business_membership_enrollment_path(@business, @membership, @enrollment), notice: 'Enrollment was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /enrollments/1
  # PUT /enrollments/1.json
  def update
    respond_to do |format|
      if @enrollment.update_attributes(enrollment_params || {})
        format.html { redirect_to business_membership_enrollment_path(@business, @membership, @enrollment), notice: 'Enrollment was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /enrollments/1
  # DELETE /enrollments/1.json
  def destroy
    @enrollment.destroy

    respond_to do |format|
      format.html { redirect_to business_membership_url(@business, @membership) }
    end
  end

  private

  def get_context
    if current_user.admin?
      @context = Business
    else
      @context = current_user.businesses
    end  

    @business = @context.find(params[:business_id])
    @membership = @business.memberships.find(params[:membership_id])
    @enrollment = @membership.enrollment
  end

  def enrollment_params
    params.require(:enrollment).permit(
      :membership_id,
      :agent_id,
      :value,
      :enrolled_on,
      :transactions_attributes,
      :enrollment_transactions_attributes
    ) if params[:enrollment].present?
  end
end

app/views/enrollments/_enrollment.html.erb
<p><b><%= Enrollment.human_attribute_name(:agent) %>:</b> <%= enrollment.agent.name %></p>
<p><b><%= Enrollment.human_attribute_name(:value) %>:</b> <%= enrollment.value %></p>
<p><b><%= Enrollment.human_attribute_name(:status) %>:</b> <%= content_tag(:span, enrollment.status, :class => "label label-#{enrollment.status}") %>
	<% if !enrollment.new_record? && !enrollment.complete? %>
        <%= link_to t('actions.mark_as_paid'), new_business_membership_enrollment_payment_path(@business, enrollment.membership, enrollment), :remote => true %>
    <% elsif !enrollment.new_record? && !@business.transactions_enabled? && enrollment.complete? %>
    	 <%= link_to content_tag(:i, "", :class => "icon-trash"), business_transaction_path(@business, enrollment.trans.first), data: {:confirm => t('actions.confirm_delete')}, :method => 'delete' %>
    <% end %>
</p>

app/views/enrollments/_form.html.erb
<%= simple_form_for(@enrollment, :validate => true, :url => form_url, :html => {:class => "form-horizontal"}) do |f| %>
    <%= f.association :agent, :as => :select, :collection => @business.agents.enabled, :input_html => {'data-placeholder' => 'Please select agent',:class => "chosen"} %>
    <%= f.input :value %>
    <%= f.input :enrolled_on, :as => "string", :input_html => {:class => "datepicker_input"} %>
    <% unless @enrollment.new_record? %>
        <%= f.input :status, :as => :payment_status, :business => @business %>
    <% end %>
    <% if @business.transactions_enabled? %>
    <h3><%= Enrollment.human_attribute_name(:transactions) %></h3>
    <%= render :partial => 'nested_transactions_table', :locals => {:f => f, :transactions => @transactions} %>
    <% elsif !@enrollment.new_record? && !@enrollment.complete? %>
        <%= link_to t('actions.mark_as_paid'), new_business_membership_enrollment_payment_path(@business, f.object.membership, f.object), :remote => true %>
    <% end %>
    <%= f.button :submit, :class => "btn btn-primary" %>
<% end %>

app/views/enrollments/edit.html.erb
<% content_for :sidebar do %>
<% end %>

<h2>Edit Enrollment</h2>

<%= render :partial => 'form', :locals => {:form_url => business_membership_enrollment_path(@business, @membership)} %>

<%= link_to 'Show', business_membership_enrollment_path(@business, @membership) %> |
<%= link_to 'Back', business_membership_path(@business, @membership) %>

app/views/enrollments/new.html.erb
<% content_for :sidebar do %>
<% end %>

<h2><%= t('enrollments.new.title') %></h2>

<%= render :partial => 'form', :locals => {:form_url => business_membership_enrollment_path(@business, @membership)}  %>

<%= link_to t('actions.back'), business_membership_path(@business, @membership) %>

app/views/enrollments/show.html.erb
<% content_for :sidebar do %>
<% end %>

<h2><%= Enrollment.model_name.human %></h2>
<%= render :partial => 'enrollment', :locals => {:enrollment => @enrollment} %>


<% if @business.transactions_enabled? %>
<h3><%= Enrollment.human_attribute_name(:transactions) %></h3>
<%= render :layout => 'transactions_table', :locals => {:transactions => @enrollment.trans} do |transaction| %>
    <%= link_to content_tag(:i, "", :class => "icon-edit"), edit_business_transaction_path(transaction.business, transaction), :remote => true %>
    <%= link_to content_tag(:i, "", :class => "icon-trash"), business_transaction_path(transaction.business, transaction), data: {:confirm => t('actions.confirm_delete')}, :method => 'delete' %>
<% end %>
<% end %>

<%= link_to t('actions.edit'), edit_business_membership_enrollment_path(@business, @membership) %> |
<%= link_to t('actions.back'), business_membership_path(@business, @membership) %>