config/routes.rb
Fnz::Application.routes.draw do
  #mount TzMagic::Engine => "/tz_magic"

  #authenticated :user do
  #  root :to => 'home#index'
  #end

  get "/login",  to: "sso_sessions#show"
  match '/logout', to: "sso_sessions#destroy", via: [:get, :delete]
  devise_for :users, :controllers => { :registrations => "registrations"}
  resource :sso_session

  resources :user_businesses
  resources :businesses do
    resources :month_tag_totals, only: [:index]
    resources :admparts do
      get "/ym/:year/:month", to: "admparts#show", as: :dated_admpart, on: :collection
      member do
        get :attendance_detail
      end
      collection do
        get :current, to: "admparts#show", id: :current
      end
    end
    resources :accounts do
      member do
        patch :update_balance
      end
      resources :transactions, :only => [:index] do
        get :stats, :on => :collection
      end
      resources :debits, :controller => 'transactions', :only => [:index]
      resources :credits, :controller => 'transactions', :only => [:index]
      resources :transfers, :controller => 'transactions', :only => [:index]
      resources :balance_checks
    end
    resources :recurrent_transactions
    resources :transactions do
      resources :transaction_spliters, only: [:new, :create] do
        collection do
          get :new_n_split
          post :create_n_split
        end
      end
      member do
        get :receipt
      end
      collection do
        get :batch_edit
        put :batch_update
        get :stats
      end
    end
    resources :debits, :controller => 'transactions', :only => [:index, :update]
    resources :credits, :controller => 'transactions', :only => [:index, :update]
    resources :transfers, :controller => 'transactions', :only => [:index, :update]
    resources :tags do
      collection do
        # required for Sortable GUI server side actions
        post :rebuild
      end
    end
    resources :month_exchange_rates do
      collection do
        get :get_rate
      end
      member do
        put :refresh_rate
      end
    end
    resources :transaction_rules
    resources :contacts
    resources :agents
    resources :products
    resources :sales do
      get :stats, :on => :collection
      resource :payment, :only => [:new, :create]
    end
    resources :payment_types
    resources :installments
    resource :payment, :only => [:new, :create]
    resources :memberships do
      resource :payment, :only => [:new, :create]
      resources :installments do
      	resource :payment, :only => [:new, :create]
      end
      resource :enrollment do
        resource :payment, :only => [:new, :create]
      end
      get :overview, :on => :collection
      get :stats, :on => :collection
      get :stats_detail, :on => :collection
    end
    resources :inscriptions do
      resources :transactions
    end
    resources :imports do
      put :process_csv, :on => :member
      get :errors, :on => :member
    end
    resources :users
    resources :closures
    resource :closure do
      get :print, :on => :member
    end
  end
  resources :debits, :controller => 'transactions', :except => [:index]
  resources :credits, :controller => 'transactions', :except => [:index]
  resources :transfers, :controller => 'transactions', :except => [:index]
  resources :custom_prizes

  resources :receipts
  get "/r/:id", to: "receipts#show"

  get 'messages', to: 'messages#catch_message'
  get 'sns', to: 'messages#sns'
  post 'sns', to: 'messages#sns'

  namespace 'admin' do
    resources :businesses, only: [:index, :show, :edit, :update, :destroy]
  end

  namespace 'api' do
    namespace 'v0' do
      resources :imports, only: [:create, :show] do
        member do
          get :failed_rows # GET /api/v0/imports/:id/failed_rows
        end
      end
      resources :businesses do
        resources :contacts do
          resource :current_membership
        end
	      get 'current_memberships', to: "current_memberships#index"
      end
      resources :merges, only: [:create]
      resources :inscriptions, only: [:create]
      namespace 'notifications' do
        post :mercadopago
      end
    end
  end

  root to: "home#index"
end

app/models/business.rb
class Business < ActiveRecord::Base

  include HasCurrency
  include Business::HasContacts

  belongs_to :owner, :class_name => "User"
  has_many :accounts
  has_many :recurrent_transactions, class_name: "RecurrentTransaction"
  has_many :receipts
  has_many :trans, class_name: "Transaction"
  has_many :transaction_rules
  has_many :tags
  has_many :agents
  has_many :products
  has_many :imports
  has_many :product_imports
  has_many :sale_imports
  has_many :membership_imports
  has_many :installment_imports
  has_many :payment_types
  has_and_belongs_to_many :users, join_table: 'businesses_users'

  has_many :month_exchange_rates

  validates :name, :presence => true
  validates :owner, :presence => true
  
  # Setup accessible (or protected) attributes for your model
  #attr_accessible :type, :name, :owner_id, :padma_id, :synchronized_at, :send_weekly_reports, :transactions_enabled, :share_enabled, :use_calendar_installments, :currency_code

  after_create :initialize_feature_flags
  after_save :link_to_owner

  def link_to_owner
    unless(self.owner.business_ids.include?(self.id))
      self.owner.businesses << self
    end
  end

  def padma
    PadmaAccount.find(padma_id) if padma_id
  end

  def time_zone
    Rails.cache.fetch("time_zone_business_#{self.id}") do
      self.padma.try(:timezone)
    end
  end

  def initialize_feature_flags
    if type == "School"
      update_attributes({
        :transactions_enabled => false,
        :share_enabled => true
      })
    else
      update_attributes({
        :transactions_enabled => true,
        :share_enabled => false
      })
    end
  end

  def self.smart_find(id_or_padma_id)
    param_is_padma_id = (false if Float(id_or_padma_id) rescue true)
    if param_is_padma_id
      self.get_by_padma_id(id_or_padma_id)
    else
      self.find(id_or_padma_id)
    end
  end

  def self.get_from_scope(scope)
    scope = scope.where(nil)
    res = scope.to_sql.match(/business_id\" \= (\d+)/)
    (res)? find(res[1].to_i) : nil
  end

  def self.get_by_padma_id(padma_id)
    b = self.find_by_padma_id(padma_id)
    if b.nil?
      b = School.new(padma_id: padma_id)
      begin
        PadmaAccountsSynchronizer.new(b).sync
      rescue
        b = nil
      end
    end
    b
  end

  def self.current=(b)
    Thread.current[:current_business] = b
  end

  def self.current
    Thread.current[:current_business]
  end

end

app/models/transaction/receiptable.rb
module Transaction::Receiptable
  extend ActiveSupport::Concern

  included do

    belongs_to :receipt

    attr_accessor :receipt_on_create, :receipt_email

    def can_receipt?
      is_a?(Credit) && state != "pending"
    end

    # @return [Receipt]
    def generate_receipt
      r = business.receipts.create(
        email: receipt_email,
        contact_id: contact_id,

        description: description,
        amount_cents: amount_cents,
        currency_id: source.currency_code,
        ref_date: transaction_at,
      )
      self.update_columns(receipt_id: r.id) if r.persisted?
      r
    end

    private

    def receipt_date
      (state == "reconciled") ? reconciled_at : transaction_at
    end

  end
end

app/controllers/transactions_controller.rb
class TransactionsController < UserApplicationController
  include ReceiptsHelper

  before_filter :get_context

  PER_PAGE = 200
  def index
    @context = @context.order("order_stamp DESC")

    @transactions = @context.includes(:agent, :contact, :tags, :source, :business)

    if @account && @start_date
      @starting_balance = @account.calculate_balance_cents(@start_date) / 100.0
    end

    if @account && @end_date && @end_date < Time.zone.today
      eb = @account.calculate_balance_cents(@end_date) / 100.0
      if eb != @account.balance
        @ending_balance = eb
      end
    end

    if @tag && @report_date
      @dates = []
      @tree_totals = { }

      last_date = if @report_date < Date.today.beginning_of_month
        Date.today.beginning_of_month
      else
        @report_date
      end

      rd = last_date
      while rd > @report_date-3.months
        @dates << rd
        [@tag,@tag.children].flatten.each do |tag|
          @tree_totals[tag] = {} if @tree_totals[tag].nil?
          @tree_totals[tag][rd] = tag.month_total(rd)
        end
        rd = rd-1.month
      end
    end

    respond_to do |format|
      format.html do
        get_download_api_key
        @transactions = @transactions.page(params[:page]).per(params[:per_page] || PER_PAGE )
      end
      format.csv do
        headers['Content-Disposition'] = "attachment; filename=\"transactions.csv\""
        headers['Content-Type'] ||= 'text/csv'
      end
    end
  end

  def show
    @transaction = Transaction.find(params[:id])
  end

  def edit
    @transaction = Transaction.find(params[:id])
  end

  def new
    @transaction = @context.new(transaction_attributes_for_new)
    if params[:quick]
      render layout: "quick_mobile"
    end
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @transaction = @context.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        return_to_url = if params[:quick]
          # boolean casting is rails 4.2 specific
          if @transaction.can_receipt? && ActiveRecord::Type::Boolean.new.type_cast_from_database(@transaction.receipt_on_create)
            receipt_business_transaction_path(@business, @transaction)
          else
            new_business_transaction_path(@business, quick: 1)
          end
        else
          business_transaction_path(@business, @transaction)
        end
        format.html { redirect_to return_to_url, notice: _('Movimiento creado') }
        format.json { render json: @transaction, status: :created, location: business_transaction_path(@business, @transaction) }
        format.js {}
      else
        format.html { render action: "new" }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
        format.js {}
      end
    end
  end

  # PUT /accounts/1
  # PUT /accounts/1.json
  def update
    @transaction = Transaction.find(params[:id])
    authorize! :update, @transaction

    respond_to do |format|
      if @transaction.update_attributes(transaction_attributes_for_update || {})
        format.html { redirect_to business_transaction_path(@business, @transaction), notice: _("Movimiento actualizado") }
        format.js {}
        format.json do
          respond_with_bip(@transaction.becomes(Transaction), param: transaction_param_key)
        end
      else
        format.html { render action: "edit" }
        format.js {}
        format.json { respond_with_bip(@transaction.becomes(Transaction), param: transaction_param_key) }
      end
    end
  end

  def batch_edit
    @transaction = Transaction.new
    @transaction.state = ""
    respond_to do |format|
      format.js
    end
  end
  def batch_update
    @transactions = Transaction.where(id: params[:ids])
    @transactions.each { |t| authorize! :update, t }
    @success = true
    @transactions.find_each{|t| @success &&= t.update_attributes(transaction_attributes_for_batch_update) } # trigger callbacks
    respond_to do |format|
      format.js 
    end
  end


  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @transaction = Transaction.find(params[:id])
    authorize! :destroy, @transaction

    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
  end

  def receipt
    @transaction = @business.trans.find(params[:id])
    if (@receipt = @transaction.receipt).nil?
      @receipt = @transaction.generate_receipt
    end

    redirect_to public_receipt_url(@receipt)
  end

  private

  def transaction_param_key
    if params[:credit]
      :credit
    elsif params[:debit]
      :debit
    elsif params[:transfer]
      :transfer
    else
      :transaction
    end
  end

  def transaction_attributes_for_new
    attrs = ( transaction_params || {}).reverse_merge({
      type: 'Debit',
      transaction_at: Time.zone.now
    })
    if @business
      attrs = attrs.reverse_merge({
        source_id: @business.accounts.where(default: true).first.try(:id)
      })
    end
    attrs.is_a?(ActionController::Parameters) ? attrs.permit! : attrs
  end

  def transaction_attributes_for_update
    transaction_params
  end

  def transaction_attributes_for_batch_update
    # TODO remove blanks
    params.require(:transaction).reject{|k,v| v.blank? }.permit!
  end

  def get_context
    business_id = params[:business_id]
    source_id = params[:account_id]

    if current_user.admin?
      @business_context = Business
    else
      @business_context = current_user.businesses
    end

    @context = Transaction
    if business_id
      @business = @business_context.find(business_id)
      @context = @business.trans
      if source_id
        @account = @business.accounts.find(source_id)
        if params[:active_only]
          @context = @account.active_transactions
        else
          @context = @account.trans
        end
      end
    end

    if params[:transaction_search]
      @transaction_search = TransactionSearch.new({base_scope: @context, business_id: @business.id}.merge(params[:transaction_search]))
      if @transaction_search.period_filter?
        @meta_period = @transaction_search.smart_meta_period
      end
      @context = @transaction_search.results
    else
      @transaction_search = TransactionSearch.new(base_scope: @context)
      @meta_period = params[:meta_period] || "current_month"
      @start_date = Date.parse(params[:start_date] || Time.zone.today.beginning_of_month.to_s).beginning_of_day
      if params[:end_date] == "Invalid date"
        params[:end_date] = nil
      end
      @end_date = Date.parse(params[:end_date] || Time.zone.today.end_of_month.to_s).end_of_day

      if params[:report_on]
        @report_date = Date.parse( params[:report_on] )
        @context = @context.to_report_on_month(@report_date)
      else
        # List transactions that ocurred on that month or that are pending and ocurred before or that are reconciled on that month
        @context = @context.where("(transaction_at >= :start AND transaction_at <= :end) OR (state = 'pending' AND transaction_at <= :start) OR (state = 'reconciled' AND reconciled_at >= :start AND reconciled_at <= :end)", {start: @start_date.to_time, end: @end_date.to_time})
      end
    end

    if params[:admpart_tag_id]
      @tag = Tag.find params[:admpart_tag_id]
      @context = @context.where(admpart_tag_id: @tag.self_and_descendants.map(&:id))
    end

    @context = @context.api_where(filter_params)
  end

  def filter_params
    if params[:q]
      params.require(:q).permit!
    end
  end

  def get_download_api_key
    return if @business.nil?

    if @download_api_key
      @download_api_key
    else
      possible_keys = ApiKey.paginate(where: {
        account_name: @business.padma_id,
        access: [:public_downloads, :login_key]
      })
      if possible_keys
        mine = possible_keys.select{|ak| ak.username == current_user.username }.first
        @download_api_key = if mine
          mine.try(:key)
        else
          possible_keys.last.try(:key)
        end
      end
    end
  end

  def transaction_params
    params.require(transaction_param_key).permit(
      :tag_id,
      :description,
      :business_id,
      :source_id,
      :amount,
      :type,
      :transaction_at,
      :target_id,
      :conversion_rate,
      :state,
      :reconciled_at,
      :sale_ids,
      :installment_ids,
      :enrollment_ids,
      :creator_id,
      :report_at,
      :report_at_option,
      :inscription_ids,
      :contact_id,
      :agent_id,
      :admpart_tag_id,
      :tag_ids,
      :receipt_on_create,
      tag_ids: []
    ) if params[transaction_param_key].present?
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper

  def bip_tag_id(transaction)
    best_in_place transaction,
                  :tag_id,
                  as: :select,
                  collection: tag_options_for_select,
                  url: business_transaction_path(@business, transaction)
  end

  def accounts_options_for_select
    @accounts_options_for_select ||= @business.accounts.order("name").map {|i| [i.id, i.name]}
  end

  def tag_options_for_select
    @tag_options_for_select ||= @business.tags.order(:name).map{|t| [t.id, t.name]}
  end

  def inverted_tag_options_for_select
    @inverted_tag_options_for_select ||= tag_options_for_select.map{|o| [o[1],o[0]]}
  end

  def agent_options_for_select(transaction=nil)
    @agent_options_for_select ||= [["",""]]+@business.agents.enabled.map { |i| [i.id, i.name] }
    if transaction && !transaction.agent_id.in?(@agent_options_for_select.map{|a| a[0] })
      @agent_options_for_select << if transaction.agent
        [transaction.agent.id,transaction.agent.name]
      else
        [transaction.agent_id,"??????"]
      end
    end
    @agent_options_for_select
  end
  
  def contact_options_for_select
    @contact_options_for_select ||= [["",""]]+@business.contacts.order(:name).map { |i| [i.id, i.name] }
  end

  def export_to_drive_formula
    csv_url = business_transactions_url(@business, params.merge({secret_key_login: @download_api_key, format: "csv", csv_options: { col_sep: "," }, ts: 1})).gsub("http:","https:")
    "=IMPORTDATA(\"#{csv_url}\")"
  end
end

app/views/transactions/_append_transaction_on_index.js.erb
$('.transactions.table tbody').prepend("<tr data-target='filter.item sum_filtered.row' id='transaction_row_<%= @transaction.id %>' data-id='<%= @transaction.id %>'><%= escape_javascript render(:partial => 'application/transactions_table_item', :locals => {:transaction => @transaction}) %><td><%= escape_javascript link_to(content_tag(:i, '', :class => 'icon-edit'), business_transaction_path(@transaction.business, @transaction)) %> <%= escape_javascript link_to(content_tag(:i, '', :class => 'icon-trash'), business_transaction_path(@transaction.business, @transaction), :confirm => _('¿Seguro que desea eliminar esta transacción?'), :method => 'delete') %> <%= escape_javascript(link_to(content_tag(:i, "", class: "icon-cut"), new_business_transaction_transaction_spliter_path(@transaction.business, @transaction), remote: true)) if can?(:split, @transaction) %> <%= escape_javascript(link_to(content_tag(:i, "", class: "icon-file"), receipt_business_transaction_path(@business, @transaction), target: :_blank)) if @transaction.can_receipt? %></td></tr>")

jQuery("#transaction_row_<%= @transaction.id %> .best_in_place").best_in_place();

app/views/transactions/_form.html.erb
<div id="quickForm">
<%= simple_form_for(@transaction,
                    as: :transaction,
                    url: form_url,
                    validate: true,
                    html: {
                      class: "transactionFields",
                      data: {
                        controller: "transaction-form",
                        "transaction-form-rates-url": get_rate_business_month_exchange_rates_path(@business)
                      }
                    }
    ) do |f| %>
    <div id="colorSignal" data-target="transaction-form.colorSignal"></div>
      <input type="hidden" name="quick" value="1"></input>

      <%= render partial: 'fields', locals: {:f => f} %>

      <%= f.button :submit, t("actions.create"), class: "btn btn-primary" %>
<% end %>
</div>

app/views/transactions/_new_modal.html.erb
<div id="new-transaction-modal" class = "modal hide fade">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3><%= _("Registrar transacción") %></h3>
  </div>
  <%= simple_form_for(@transaction,
    as: :transaction,
    url: business_transactions_path(@business),
    validate: true,
    remote: true,
    html: {
      class: 'form-horizontal transactionFields',
      data: {
        controller: "transaction-form",
        "transaction-form-rates-url": get_rate_business_month_exchange_rates_path(@business)
    }
      }) do |f| %>
      <%= render partial: 'transactions/fields', locals: {:f => f} %>
      <% %w(sale installment enrollment inscription).each do |nested_resource_type| %>
          <% f.object.send("#{nested_resource_type}_ids").each_with_index do |nested_resource_id, index| %>
            <%= f.input "#{nested_resource_type}_ids", as: :hidden, input_html: {id: "#{nested_resource_type}_ids_#{index}", name: "transaction[#{nested_resource_type}_ids][]", value: nested_resource_id} %>
          <% end %>
      <% end %>
      <div class="modal-footer" data-target="transaction-form.colorSignal">
        <%= link_to t('actions.close'), "#", class: "btn", "data-dismiss" => "modal" %>
        <%= f.button :submit, t("actions.create"), class: "btn btn-primary", id: "submitTransaction" %>
      </div>
  <% end %>
</div>

app/views/transactions/_update_account_balance.js.erb
if($(".account_<%= account.id %>_balance").length > 0){
  $(".account_<%= account.id %>_balance").html("<%= number_to_currency(account.balance, unit: account.currency.symbol) %>");
}

app/views/transactions/batch_edit.js.erb
<% if params[:ids].blank? %>
    alert("<%= _("Seleccioná algunas transacciones") %>");
<% else %>
$('#batch-edit-transaction-modal').remove();
$('body').append("<%= escape_javascript(render(partial: "transactions/batch_edit_modal"))%>");
$('#batch-edit-transaction-modal').modal({
    keyboard: false
});
$("#edit_transaction #transaction_tag_ids").chosen({
    no_results_text: "No results matched",
    create_option: function(term){
        var chosen = this;
        $.post('<%= business_tags_path(@business, :format => :json) %>', {tag: { name: term}}, function(data){
            chosen.append_option({
                value: data.id,
                text: data.name
            });
        });
    },
    persistent_create_option: true
});
<% end %>

app/views/transactions/batch_update.js.erb
$('#batch-edit-transaction-modal').modal('hide').remove();

<% @transactions.each do |transaction| %>
  $('.transactions.table tr[data-id=<%= transaction.id %>]').html("<%= escape_javascript render(partial: 'application/transactions_table_item', locals: {transaction: transaction}) %> <td><%= escape_javascript link_to(content_tag(:i, '', class: 'icon-edit'), business_transaction_path(transaction.business, transaction)) %> <%= escape_javascript link_to(content_tag(:i, '', class: 'icon-trash'), business_transaction_path(transaction.business, transaction), confirm: _("¿Seguro que querés eliminar esta transacción? No podrá ser recuperada."), method: 'delete') %></td>");
  <% if transaction.source_id %>
    <%= render partial: "update_account_balance", locals: { account: transaction.source } %>
  <% end %>

  <% if transaction.target_id %>
    <%= render partial: "update_account_balance", locals: { account: transaction.target } %>
  <% end %>
<% end %>

app/views/transactions/create.js.erb
<% if @transaction.persisted? %>
$('#new-transaction-modal').modal('hide').remove();

if ($(".nested.transactions.table tbody").length > 0) {
  $('.nested.transactions.table tbody').prepend("<tr data-target='filter.item sum_filtered.row' data-id='<%= @transaction.id %>'><%= escape_javascript render(:partial => 'application/transactions_table_item', :locals => {:transaction => @transaction}) %><td><%= escape_javascript link_to(content_tag(:i, '', :class => 'icon-remove'), '#', :class => 'remove-nested-transaction') %></td></tr>")
} else if($(".transactions.table tbody").length > 0) {
    <%= render partial: "append_transaction_on_index" %>
} else {
  window.location = '<%= business_transactions_path(@business) %>'
}

<% if @transaction.source_id %>
  <%= render partial: "update_account_balance", locals: { account: @transaction.source } %>
<% end %>

<% if @transaction.target_id %>
  <%= render partial: "update_account_balance", locals: { account: @transaction.target } %>
<% end %>
<% else %>
  <%# ERROR creating transaction %>
  alert("error creating transaction <%= @transaction.errors.full_messages.to_sentence %>");
  $("#submitTransaction").attr("disabled",false); // re-enable submit button
<% end %>

app/views/transactions/index.html.erb
<%
  title = if @tag
    @tag.name
  elsif @account
    @account.name
  else
    _("Transacciones")
  end
%>
<% page_title title %>

<% content_for :head do %>
  <meta http-equiv="refresh" content="<%= 15.minutes %>" >
<% end %>
<% content_for :sidebar do %>
    <%= render :partial => 'businesses/sidebar' %>
<% end %>

<% content_for :secondary_navigation do %>
    <%= render :partial => 'secondary_navigation' %>
<% end %>

<% content_for :top do %>
  <button data-action="sidebar#toggleSideBar" data-target="sidebar.toggler" data-show-msg="<%= _("mostrar") %>" data-hide-msg="<%= _("ocultar") %>" class="btn hide-in-print"><span data-target="sidebar.togglerVerb"></span> <%= _("cuentas") %></button>
<% end %>

<% if @tag and @report_date %>
  <%= render "tag_summary" %>
<% end %>

<div class="row-fluid hide-in-print">
  <%= render 'search_form' %>
</div>

<%= form_tag batch_edit_business_transactions_path(@business), method: :get, remote: true, "data-controller" => "filter transactions_table" do %>
<div class="actions row-fluid hide-in-print">
  <% if can? :create, @business.imports.build %>
    <%= link_to content_tag(:i, "", class: "icon-upload") + I18n.t('transactions.index.import'),
      new_business_import_path(@business, import: { account_id: @account.try(:id) }),
                class: "btn" %>
  <% end %>
  <%= submit_tag _("Editar"), class: "btn" %>

  <div class="pull-right">
    <%= link_to content_tag(:i, "", class: "icon-download"), business_transactions_path(@business, params.merge({format: "csv"})), class: "btn" %>
    <%= render partial: "drive_button" %>
  </div>
  <span class="control-group pull-right" data-controller="quick_meta_filter">
    <span class="controls">
      <span class="input-prepend">
    	<span class="add-on icon-calendar"></span>
        <%= select_tag "quick_meta_period", options_for_select({
          "" => nil,
          t(".current_month") => "current_month",
          t(".previous_month") => "previous_month",
          t(".month_before_last") => "month_before_last"
        }, @meta_period), data: {target: "quick_meta_filter.selector" , action: "quick_meta_filter#goToPeriod"} %>
  	  </span>
    </span>
  </span>

  <%= render "balance_title" %>
</div>

<div class="row-fluid hide-in-print">
  <div class="span10"></div>
  <div id="filterContainer" class="span2">
    <input type="text" id="transactionsFilter" data-target="filter.query" data-action="keyup@window->filter#filterItems" disabled></input>
    <span id="datelessSearch" class="icon-filter"></span>
  </div>
</div>

<%= render layout: 'transactions_table', locals: {transactions: @transactions} do |transaction| %>
  <span class="hide-in-print">
  <% if can? :edit, transaction %>
    <%= link_to content_tag(:i, "", class: "icon-edit"), edit_business_transaction_path(transaction.business, transaction), remote: true %>
  <% end %>
  <% if can? :destroy, transaction %>
    <%= link_to content_tag(:i, "", class: "icon-trash"), business_transaction_path(transaction.business, transaction), data: {confirm: I18n.t('actions.confirm_delete')}, method: 'delete', remote: true %>
  <% end %>
  <% if can? :split, transaction %>
    <%= link_to content_tag(:i, "", class: "icon-cut"), new_business_transaction_transaction_spliter_path(transaction.business, transaction), remote: true %>
  <% end %>
  <% if transaction.can_receipt? %>
    <%= link_to content_tag(:i, "", class: "icon-file"), receipt_business_transaction_path(@business, transaction), target: :_blank %>
  <% end %>
  </span>
<% end %>
<div id="pagination">
<%= paginate @transactions %>
</div>
<% end %>

<% if params[:active_only] %>
  <div class="alert alert-notice">
    <p>
      <%= _("Mostrando solo los movimientos que hubo después del último cierre de caja y que afectan al saldo") %>.<br/>
      <% if @account.last_balance_check %>
        <b><%= number_to_currency @account.last_balance_check.balance, unit: @account.currency.symbol %> @ <%= l @account.last_balance_check.checked_at, format: :short %></b>
      <% end %>
    </p>
    <p>
      <%= link_to _("volver a %{account}") % { account: @account.name } , business_account_transactions_path(@business,@account) %>
    </p>
  </div>
<% end %>

app/views/transactions/show.html.erb
<% content_for :sidebar do %>
    <%= render :partial => 'businesses/sidebar' %>
<% end %>

<% content_for :secondary_navigation do %>
    <%= render :partial => 'secondary_navigation' %>
<% end %>

<h3>Transaction</h3>
<p>Type: <%= @transaction.type %></p>
<p>Business: <%= @transaction.business.name %></p>
<p>Source: <%= @transaction.source.name %></p>
<p>Description: <%= @transaction.description %></p>
<p>Amount: <%= @transaction.amount %></p>
<p>Date: <%= @transaction.transaction_at %></p>
<p>Tags:
<ul>
  <% @transaction.tags.each do |tag| %>
  <li><%= tag.name %></li>
  <% end %>
</ul>
</p>

<%= link_to 'Edit', edit_business_transaction_path(@transaction.business, @transaction) %> |
<%= link_to 'Back',:back %>