config/routes.rb
Fnz::Application.routes.draw do
  #mount TzMagic::Engine => "/tz_magic"

  #authenticated :user do
  #  root :to => 'home#index'
  #end

  get "/login",  to: "sso_sessions#show"
  match '/logout', to: "sso_sessions#destroy", via: [:get, :delete]
  devise_for :users, :controllers => { :registrations => "registrations"}
  resource :sso_session

  resources :user_businesses
  resources :businesses do
    resources :month_tag_totals, only: [:index]
    resources :admparts do
      get "/ym/:year/:month", to: "admparts#show", as: :dated_admpart, on: :collection
      member do
        get :attendance_detail
      end
      collection do
        get :current, to: "admparts#show", id: :current
      end
    end
    resources :accounts do
      member do
        patch :update_balance
      end
      resources :transactions, :only => [:index] do
        get :stats, :on => :collection
      end
      resources :debits, :controller => 'transactions', :only => [:index]
      resources :credits, :controller => 'transactions', :only => [:index]
      resources :transfers, :controller => 'transactions', :only => [:index]
      resources :balance_checks
    end
    resources :recurrent_transactions
    resources :transactions do
      resources :transaction_spliters, only: [:new, :create] do
        collection do
          get :new_n_split
          post :create_n_split
        end
      end
      member do
        get :receipt
      end
      collection do
        get :batch_edit
        put :batch_update
        get :stats
      end
    end
    resources :debits, :controller => 'transactions', :only => [:index, :update]
    resources :credits, :controller => 'transactions', :only => [:index, :update]
    resources :transfers, :controller => 'transactions', :only => [:index, :update]
    resources :tags do
      collection do
        # required for Sortable GUI server side actions
        post :rebuild
      end
    end
    resources :month_exchange_rates do
      collection do
        get :get_rate
      end
      member do
        put :refresh_rate
      end
    end
    resources :transaction_rules
    resources :contacts
    resources :agents
    resources :products
    resources :sales do
      get :stats, :on => :collection
      resource :payment, :only => [:new, :create]
    end
    resources :payment_types
    resources :installments
    resource :payment, :only => [:new, :create]
    resources :memberships do
      resource :payment, :only => [:new, :create]
      resources :installments do
      	resource :payment, :only => [:new, :create]
      end
      resource :enrollment do
        resource :payment, :only => [:new, :create]
      end
      get :overview, :on => :collection
      get :stats, :on => :collection
      get :stats_detail, :on => :collection
    end
    resources :inscriptions do
      resources :transactions
    end
    resources :imports do
      put :process_csv, :on => :member
      get :errors, :on => :member
    end
    resources :users
    resources :closures
    resource :closure do
      get :print, :on => :member
    end
  end
  resources :debits, :controller => 'transactions', :except => [:index]
  resources :credits, :controller => 'transactions', :except => [:index]
  resources :transfers, :controller => 'transactions', :except => [:index]
  resources :custom_prizes

  resources :receipts
  get "/r/:id", to: "receipts#show"

  get 'messages', to: 'messages#catch_message'
  get 'sns', to: 'messages#sns'
  post 'sns', to: 'messages#sns'

  namespace 'admin' do
    resources :businesses, only: [:index, :show, :edit, :update, :destroy]
  end

  namespace 'api' do
    namespace 'v0' do
      resources :imports, only: [:create, :show] do
        member do
          get :failed_rows # GET /api/v0/imports/:id/failed_rows
        end
      end
      resources :businesses do
        resources :contacts do
          resource :current_membership
        end
	      get 'current_memberships', to: "current_memberships#index"
      end
      resources :merges, only: [:create]
      resources :inscriptions, only: [:create]
      namespace 'notifications' do
        post :mercadopago
      end
    end
  end

  root to: "home#index"
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :business
  belongs_to :contact
  belongs_to :agent
  belongs_to :product

  has_many :sale_transactions
  has_many :trans, foreign_key: 'transaction_id', class_name: "Transaction", :through => :sale_transactions

  validates :business, :presence => true
  validates :agent, :presence => true
  validates :sold_on, :presence => true

  # Setup accessible (or protected) attributes for your model
  #attr_accessible :contact_id, :business_id, :agent_id, :product_id, :transactions_attributes, :sale_transactions_attributes, :sold_on, :external_id
  accepts_nested_attributes_for :trans, allow_destroy: true
  accepts_nested_attributes_for :sale_transactions, :reject_if => proc { |s| s['transaction_id'].blank? }

  scope :this_month, -> { where {(sold_on.gteq Date.today.beginning_of_month.beginning_of_day) & (sold_on.lteq Date.today.end_of_month.end_of_day)} }
  default_scope { order("sold_on DESC") }

  include BelongsToPadmaContact

  def self.build_from_csv(business, row)
    return if Sale.find_by_external_id(row[0].to_i)

    product = business.products.find_by_external_id(row[1].to_i)
    agent_id = row[2].gsub!(' ','')
    agent = business.agents.find_by_padma_id(agent_id) # some ids have spaces between
    unless agent
      agent_name = agent_id.blank? ? "Unknown" : agent_id.gsub('.',' ').titleize
      agent = business.agents.create(:padma_id => agent_id, :name => agent_name)
    end

    padma_contact = nil
    contact = nil
    unless row[3].blank?
      padma_contact = CrmLegacyContact.find_by_kshema_id(row[3])
      contact = Contact.find_or_create_by(:padma_id => padma_contact.id,
                                                 :business_id => business.id,
                                                 :name => "#{padma_contact.first_name} #{padma_contact.last_name}".strip,
                                                 :padma_status => padma_contact.status,
                                                 :padma_teacher => padma_contact.global_teacher_username)
    end

    sale_date = DateTime.parse(row[5])

    sale_attributes = {
        :business_id => business.id,
        :agent_id => agent.id,
        :sold_on => sale_date,
        :external_id => row[0].to_i
    }

    if contact
      sale_attributes[:contact_id] = contact.id
    end

    if product
      sale_attributes[:product_id] = product.id
    end

    unless row[10].blank? || row[10] == 'false' || row[8].to_i <= 0
    	#paid installment, create correspondig transaction
    	transaction_date = row[9].present? ? Date.parse(row[9]) : sale_date
    	transaction_attrs = {
    		:transaction_at => transaction_date,
    		:amount => row[8].to_f/100.0,
    		:source_id => business.accounts.first.id,
    		:business_id => business.id,
    		:description => "Payment - #{contact.try(:name)} - #{product.try(:name)}",
      		:type => "Credit",
      		:creator_id => business.owner_id
      	}

      	sale_attributes[:trans_attributes] = [transaction_attrs]
    end

    sale = Sale.new(sale_attributes)

    return sale
  end

  def self.csv_header
    "id,producto_id,instructor_id,persona_id,notes,fecha,created_at,updated_at,precio_in_cents,fecha_pago,pago,school_id,currency,forma_id".split(',')
  end

  def pending?
    !trans.empty? && trans.any? { |t| t.pending? }
  end

  def complete?
    !trans.empty? && trans.all? { |t| t.created? || t.reconciled? }
  end

  def status
    if pending?
      :pending
    elsif complete?
      :complete
    else
      :incomplete
    end
  end

end

app/controllers/sales_controller.rb
class SalesController < UserApplicationController

  before_filter :get_context

  def index
    # List transactions on this month or the year/month solicited
    start_date = @start_date = Date.parse(params[:start_date] || Date.today.beginning_of_month.to_s).beginning_of_day
    end_date = @end_date = Date.parse(params[:end_date] || Date.today.end_of_month.to_s).end_of_day

    @sales = @context.where {(sold_on.gteq start_date) & (sold_on.lteq end_date)}
  end

  def show
    @sale = @context.find(params[:id])
    @business = @sale.business
  end

  def edit
    @sale = @context.find(params[:id])
    @business = @sale.business
    date = @sale.sold_on
    @transactions = @business.trans.credits.where {(transaction_at.gteq(date - 1.month)) & (transaction_at.lteq(date + 1.month))}.order("order_stamp DESC")
  end

  def new
    @sale = @context.new(sale_params)
    date = Date.today
    @transactions = @business.trans.credits.where {(transaction_at.gteq(date - 1.month)) & (transaction_at.lteq(date + 1.month))}.order("order_stamp DESC")
  end

  # POST /accounts
  # POST /accounts.json
  def create
    padma_contact_id = params[:sale].delete(:padma_contact_id)
    @sale = @context.new(sale_params)
    @business = @sale.business

    # Setting padma_contact_id is performed last as it depends on business_id being already set
    @sale.padma_contact_id = padma_contact_id if padma_contact_id.present?

    respond_to do |format|
      if @sale.save
        format.html { redirect_to business_sale_path(@business, @sale), notice: 'Sale was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /accounts/1
  # PUT /accounts/1.json
  def update
    @sale = @context.find(params[:id])
    @business = @sale.business

    respond_to do |format|
      if @sale.update_attributes(sale_params || {})
        format.html { redirect_to business_sale_path(@business, @sale), notice: 'Sale was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @sale = @context.find(params[:id])
    @business = @sale.business unless @business
    @sale.destroy

    respond_to do |format|
      format.html { redirect_to business_sales_url(@business) }
    end
  end

  def stats
    @stats = SaleStats.new(:business => @business, :year => params[:year].to_i, :month => params[:month].to_i)
  end

  private

  def get_context
    business_id = params[:business_id]

    if current_user.admin?
      @business_context = Business
    else
      @business_context = current_user.businesses
    end

    @context = Sale
    if business_id
      @business = @business_context.find(business_id)
      @context = @business.sales
    end
  end

  def sale_params
    params.require(:sale).permit(
      :contact_id,
      :business_id,
      :agent_id,
      :product_id,
      :sold_on,
      :external_id,
      :transactions_attributes,
      :sale_transactions_attributes
    ) if params[:sale].present?
  end
end

app/views/sales/_form.html.erb
<%= simple_form_for(@sale, :url => form_url, :validate => true, :html => {:class => "form-horizontal"}) do |f| %>
	<% if @business.padma_id.blank? %>
    	<%= f.association :contact, :as => :select, :collection => @business.contacts, :input_html => {'data-business-id' => @business.id, 'data-placeholder' => t('sales.form.contact_placeholder'),:class => "chosen"} %>
    <% else %>
        <%= f.input :padma_contact_id, :as => :padma_contact %>
    <% end %>

    <%= f.association :agent, :as => :select, :collection => @business.agents.enabled, :input_html => {'data-placeholder' => t('sales.form.agent_placeholder'), :class => "chosen"} %>

    <%= f.association :product, :as => :select, :collection => @business.products, :input_html => {'data-business-id' => @business.id, 'data-placeholder' => t('sales.form.product_placeholder') ,:class => "chosen"} %>

    <%= f.input :sold_on, :as => :date_picker %>

    <% unless @sale.new_record? %>
        <%= f.input :status, :as => :payment_status, :business => @business %>
    <% end %>
    
    <% if @business.transactions_enabled? %>
    <h3><%= Sale.human_attribute_name(:transactions) %></h3>
    <%= render :partial => 'nested_transactions_table', :locals => {:f => f, :transactions => @transactions} %>
    <% elsif !@sale.new_record? && !@sale.complete?  %>
        <%= link_to t('actions.mark_as_paid'), new_business_sale_payment_path(@business, f.object), :remote => true %>
    <% end %>
    <%= f.button :submit, :class => "btn btn-primary" %>

<% end %>

<%= javascript_tag do %>

    function contactFormatResult(contact) {
    var markup = "<div>" + contact.name + "</div>";
    return markup;
    }

    function contactFormatSelection(contact) {
    return contact.name;
    }

    $("#sale_padma_contact_id").select2({
    placeholder: "Search contact",
    minimumInputLength: 3,
    ajax: {
    url: "http://<%= Contacts::HOST %>/v0/contacts/search_for_select",
    type: 'POST',
    dataType: 'jsonp',
    quietMillis: 100,
    data: function (term, page) { // page is the one-based page number tracked by Select2
    return {
    page: page,
    per_page: 10,
    sort: {
    first_name: "asc",
    last_name: "asc"
    },
    username: "<%= current_user.username %>",
    account_name: "<%= current_user.businesses.find(params[:business_id]).padma_id %>",
    only_name: true,
    full_text: term,
    app_key: "<%= ENV['contacts_key'] %>"
    };
    },
    results: function (data, page) {
    var more = (page * 10) < data.total; // whether or not there are more results available

    // notice we return the value of more so Select2 knows if more results can be loaded
    return {results: data.collection, more: more};
    }
    },
    initSelection: function(element, callback) {
    // the input tag has a value attribute preloaded that points to a preselected movie's id
    // this function resolves that id attribute to an object that select2 can render
    // using its formatResult renderer - that way the movie name is shown preselected
    var id=$(element).val();
    var name=$(element).attr("data-name");
    if (id!=="") {
    callback({"id": id, "name": name});
    }
    },
    formatResult: contactFormatResult, // omitted for brevity, see the source of this page
    formatSelection: contactFormatSelection, // omitted for brevity, see the source of this page
    dropdownCssClass: "bigdrop", // apply css that makes the dropdown taller
    escapeMarkup: function (m) { return m; } // we do not want to escape markup since we are displaying html in results
    });

<% end %>

app/views/sales/_secondary_navigation.html.erb
<li class="pull-right"><%= link_to content_tag(:i, "", :class => "icon-plus") + t('sales.secondary_navigation.new_sale'), new_business_sale_path(@business) %></li>

app/views/sales/_sidebar.html.erb
  <div class="control-group">
    <label class="control-label" for="inputSoldOn"><%= Sale.human_attribute_name(:sold_on) %></label>
    <div class="controls">
      <div class="input-prepend">
    	<span class="add-on icon-calendar"></span>
    	<input type="text" class="daterange form-control" id="sale_search_daterange" value='<%= "#{I18n.l(@start_date.to_date)} - #{I18n.l(@end_date.to_date)}" %>'/>
  	  </div>
    </div>
  </div>

app/views/sales/_stats_modal.html.erb
<div id="sale-stats-modal" class = "modal hide fade">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3><%= t('.title') %></h3>
  </div>
  <table class="membership-stats table table-striped table-hover table-condensed table-bordered">
    <thead>
      <tr>
        <th></th>
        <th data-toggle="tooltip" title="<%= t('.all_sales_tooltip') %>"><%= t('.all_sales') %> <%= content_tag(:i, "", :class => "icon-info-sign") %></th>
        <th data-toggle="tooltip" title="<%= t('.paid_sales_tooltip') %>"><%= t('.paid_sales') %> <%= content_tag(:i, "", :class => "icon-info-sign") %></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th><%= t('.school') %></th>
        <td><%= number_to_currency(@stats.all_sales.inject(0) {|sum, sale| sum + sale.product.price}) %></td>
        <td><%= number_to_currency(@stats.paid_sales.inject(0) {|sum, sale| sum + sale.product.price}) %></td>
      </tr>

      <% @business.agents.enabled.each do |agent| %>
      <tr>
        <th><%= agent.name %></th>
        <td><%= number_to_currency(@stats.all_sales.where('sales.agent_id' => agent.id).inject(0) {|sum, sale| sum + sale.product.try(:price)}) %></td>
        <td><%= number_to_currency(@stats.paid_sales.where('sales.agent_id' => agent.id).inject(0) {|sum, sale| sum + sale.product.try(:price)}) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <div class="modal-footer">
    <%= link_to t('actions.close'), "#", :class => "btn", "data-dismiss" => "modal" %>
  </div>
</div>

app/views/sales/edit.html.erb
<h2><%= t('sales.edit.title') %></h2>

<%= render :partial => 'form', :locals => {:form_url => business_sale_path(@business, @sale)} %>

<%= link_to t('actions.show'), business_sale_path(@business, @sale) %> |
<%= link_to t('actions.back'), :back %>

app/views/sales/index.html.erb
<% content_for :sidebar do %>
    <%= render :partial => 'sidebar' %>
<% end %>

<% content_for :secondary_navigation do %>
    <%= render :partial => 'secondary_navigation' %>
<% end %>

<h3><%= Sale.model_name.human(:count => 2) %></h3>
<% @sales.group_by{ |s| s.sold_on.beginning_of_month }.each do |date, sales| %>
  <h4>
  	<%= l(date, :format => '%B') %> <%= link_to content_tag(:i, "", :class => "icon-bar-chart", :title => t('sales.index.view_month_stats', :month => l(date, :format => "%B"))), stats_business_sales_path(@business, :year => date.year, :month => date.month), :remote => true %>
  </h4>
<table class="sales table table-striped table-hover table-condensed table-bordered">
  <thead>
  	<td><%= Sale.human_attribute_name(:sold_on) %></td>
  	<td><%= Sale.human_attribute_name(:contact) %></td>
  	<td><%= Sale.human_attribute_name(:agent) %></td>
  	<td><%= Sale.human_attribute_name(:product) %></td>
  	<td><%= Sale.human_attribute_name(:amount) %></td>
  	<td><%= Sale.human_attribute_name(:status) %></td>
  	<td></td>
  </thead>
  <% sales.each do |sale| %>
    <tr>
      <td><%= l(sale.sold_on, :format => :short) %></td>
      <td><%= sale.contact.try(:name) %></td>
      <td><%= sale.agent.name %></td>
      <td><%= sale.product.try(:name) %></td>
      <td><%= number_to_currency(sale.product.price, :unit => sale.product.price_currency.symbol) if sale.product %></td>
      <td><%= content_tag(:span, sale.status, :class => "label label-#{sale.status}") %></td>
      <td>
      	<%= link_to content_tag(:i, "", :class => "icon-eye-open"), business_sale_path(@business, sale) %>
      	<%= link_to content_tag(:i, "", :class => "icon-edit"), edit_business_sale_path(@business, sale) %>
  		<%= link_to content_tag(:i, "", :class => "icon-trash"), business_sale_path(@business, sale), data: {:confirm => t('actions.confirm_delete')}, :method => 'delete' %>
      </td>
    </tr>
  <% end %>
</table>
<% end %>

app/views/sales/new.html.erb
<h2><%= t('sales.new.title') %></h2>

<%= render :partial => 'form', :locals => {:form_url => business_sales_path(@business)} %>

<%= link_to t('actions.back'), :back %>

app/views/sales/show.html.erb
<h3><%= Sale.model_name.human %></h3>
<p><b><%= Sale.human_attribute_name(:contact) %>:</b> <%= @sale.contact.try(:name) %></p>
<p><b><%= Sale.human_attribute_name(:agent) %>:</b>: <%= @sale.agent.name %></p>
<p><b><%= Sale.human_attribute_name(:product) %>:</b> <%= @sale.product.try(:name) %></p>
<p><b><%= Sale.human_attribute_name(:sold_on) %>:</b> <%= @sale.sold_on %></p>
<p><b><%= Sale.human_attribute_name(:status) %>:</b> <%= content_tag(:span, @sale.status, :class => "label label-#{@sale.status}") %>
	<% if !@sale.complete?  %>
        <%= link_to t('actions.mark_as_paid'), new_business_sale_payment_path(@business, @sale), :remote => true %>
    <% elsif @sale.complete? && !@business.transactions_enabled? %>
    	 <%= link_to content_tag(:i, "", :class => "icon-trash"), business_transaction_path(@business, @sale.trans.first), data: {:confirm => t('actions.confirm_delete')}, :method => 'delete' %>
    <% end %>
</p>

<% if @business.transactions_enabled? %>
<%= render :layout => 'transactions_table', :locals => {:transactions => @sale.transactions} do |transaction| %>
  <%= link_to content_tag(:i, "", :class => "icon-edit"), edit_business_transaction_path(transaction.business, transaction), :remote => true %>
  <%= link_to content_tag(:i, "", :class => "icon-trash"), business_transaction_path(transaction.business, transaction), data: {:confirm => t('actions.confirm_delete')}, :method => 'delete' %>
<% end %>
<% end %>

<%= link_to t('actions.edit'), edit_business_sale_path(@business, @sale) %> |
<%= link_to t('actions.back'), :back %>

app/views/sales/stats.js.erb
$('body').append("<%= escape_javascript(render(:partial => "sales/stats_modal"))%>");
$('#sale-stats-modal').modal({
    keyboard: false
});